config/routes.rb
Rails.application.routes.draw do
  resources :books do
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 # protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :get_by_id, :only => [:show,:destroy,:edit,:update]

  def index
    @books = Book.all
  end

  def edit
    #@book = Book.find(params[:id])
  end

  def new
    #可写可不写 @book = Book.new
  end

  def create
    Book.create :name=>params[:name], :author=>params[:author]
    redirect_to books_path
  end

  def show
    #@book = Book.find(params[:id])
  end

  def update
    #@book = Book.find params[:id]
    @book.update :name=>params[:name],:author=>params[:author]
    @book.save
    redirect_to books_path
  end

  def destroy
    # @book = Book.find params[:id]
    @book.delete
    redirect_to books_path
  end

  def get_by_id
    @book = Book.find params[:id]

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.erb
<h3>编辑页</h3>

<form action="/books/<%= @book.id %>" method=POST>
  <input type='hidden' name='_method' value='PUT'/>

  书名: <input type="text" name="name" value="<%= @book.name %>"/></br>
  作者: <input type="text" name="author" value="<%= @book.author%>"/></br>
  <br/>
  <input type="submit" value="提交"/>

</form>
<br/>
<%= link_to '返回列表页', books_path%>

app/views/books/index.html.erb
<h3>列表页</h3>

<table cellspacing="30">

  <tr>
   <td>序号</td>
   <td>题目</td>
   <td>作者</td>
   <td colspan="2" align="center">操作</td>
  </tr>

  <% @books.each do |book| %>
 <tr>
     <td><%= book.id %></td>
     <td><%= link_to book.name,book  %></td>
     <td><%= book.author %></td>
     <!--此处为什么有个关键字id才可以-->
     <td><%= link_to "编辑" ,edit_book_path( :id => book.id )%></td>
     <td><%= link_to "删除" ,book, :method => :delete %></td>
 </tr>
   <% end %>

</table>
 <%= link_to "新增", new_book_path %>

app/views/books/new.html.erb
<h3>新增页</h3>

<!--此处换成get方法后无法插入到
列表页中但是在地址栏会显示参数-->
<form action="/books" method=POST>
  书名：<input type="text" name="name"/><br/>
  作者：<input type="text" name="author"/><br/>
<br/>
  <input type="submit" value="确认添加"/>
</form>

app/views/books/show.html.erb
<h3>详情页</h3>

书名:<%= @book.name %><br/>
作者:<%= @book.author %><br/>
<br/>
<%= link_to '返回列表页',books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GetRequestHomework1124</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>